os: osx
language: go
go:
  - "1.10"

before_install:
  - stty cols 80
  - wget https://github.com/macports/macports-base/releases/download/v2.5.3/MacPorts-2.5.3-10.13-HighSierra.pkg -O ports.pkg
  - sudo installer -pkg ports.pkg -target /
  - sudo /opt/local/bin/port -d selfupdate
  - sudo /opt/local/bin/port -N install gtk3
  - sudo /opt/local/bin/port -N install glib2
  - sudo /opt/local/bin/port -N install pkgconfig
  - sudo /opt/local/bin/port -N install xorg-xproto
  - sudo /opt/local/bin/port load dbus
  - sudo /opt/local/bin/port select --set python python27
  - sudo /opt/local/bin/port select --set python2 python27
  - export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig
