os: osx
language: go
go:
  - "1.10"
gobuild_args: -ldflags "-X github.com/UwUNote/uwunote/internal/updates.AppVersion=$(git describe --tags --always --dirty)"

before_install:
  - brew update
  - brew install gtk+3
