os: osx
language: go
go:
  - "1.10"

before_install:
  - wget https://github.com/macports/macports-base/releases/download/v2.5.3/MacPorts-2.5.3-10.13-HighSierra.pkg -O ports.pkg
  - sudo installer -pkg ports.pkg -target /
  - sudo /opt/local/bin/port -d selfupdate
  - sudo /opt/local/bin/port install gtk3