clone_folder: c:\gopath\src\github.com\UwUNote\uwunote

environment:
  GOPATH: c:\gopath

stack: go 1.10

artifacts:
  - path: uwunote.exe
    name: UwUNote.exe
  - path: uwunote-setup.exe
    name: uwunote-setup.exe

install:
  - SET PATH=%PATH%;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\Program Files (x86)\Inno Setup 5
  - SET MINGW_ROOT=C:\msys64\mingw64\
  - pacman --noconfirm --needed -Sy bash pacman pacman-mirrors
  - pacman --noconfirm -Su
  - pacman --noconfirm -Su
  - pacman --noconfirm -S mingw-w64-x86_64-gcc
  - pacman --noconfirm -S mingw64/mingw-w64-x86_64-pkg-config
  - pacman --noconfirm -S mingw-w64-x86_64-gtk3
  - bash -c "sed -i -e 's/-Wl,-luuid/-luuid/g' C:/msys64/mingw64/lib/pkgconfig/gdk-3.0.pc"

build_script:
  - go get ./...
  - ps: $env:UWU_VERSION=git describe --tags --always --dirty
  - ps: go build -o uwunote.exe -ldflags "-H windowsgui"
  - ps: ISCC .\windows-setup.iss

test_script:
  - go vet ./...
  - go test ./...