apt-run: &ref_0
  name: Install Linux dependecies via apt.
  command: >-
    sudo apt-get update

    sudo apt-get -y install libglib2.0-dev libgtk-3-dev libappindicator3-dev
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/UwUNote/uwunote
    steps:
      - checkout

      - run: *ref_0

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build -ldflags "-X github.com/UwUNote/uwunote/internal/updates.AppVersion=$(git describe --tags --always --dirty)"

      - store_artifacts:
          path: /go/src/github.com/UwUNote/uwunote/uwunote
          destination: uwunote