package errors

import (
	"fmt"
	"net/url"
	"runtime"

	"github.com/gotk3/gotk3/gtk"
)

//IssueTemplate for GitHub Issue
const IssueTemplate = `
<!-- This is an autogenerated issue template, please fill in the form below-->
## What did you do when the error occurred?

**FILL IN**

## Error Message

%s

## Machine Information

OS: %s
GOARCH: %s
GTK: %s

## Aditional Information

FILL IN IF PRESENT
`

//CreateIssueUrl creates a URL leading you to the "New Issue"-page of UwUNote with a prefilled issue title and body.
func CreateIssueUrl(errorMessage string) string {
	gtkVersion := fmt.Sprintf("%d.%d.%d", gtk.GetMajorVersion(), gtk.GetMinorVersion(), gtk.GetMicroVersion())
	issueTemplateFilled := fmt.Sprintf(IssueTemplate, errorMessage, runtime.GOOS, runtime.GOARCH, gtkVersion)
	linkFragment := fmt.Sprintf("?title=%s&body=%s", url.QueryEscape(errorMessage), url.QueryEscape(issueTemplateFilled))

	return "https://github.com/UwUNote/uwunote/issues/new" + linkFragment
}
