name: uwunote # you probably want to 'snapcraft register <name>'
version: '1.1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Sticky note application
description: |
  A tiny stickynote application that allows to pin plaintext notes right
  onto your desktop.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  uwunote:
    command: bin/uwunote
    plugs: [home, x11]

parts:
  go:
    source-tag: go1.10
  uwunote:
    after: [desktop-gtk3]
    source: https://github.com/UwUNote/uwunote
    source-type: git
    plugin: go
    go-importpath: github.com/UwUNote/uwunote
    build-packages:
      - libgtk-3-dev
      - libglib2.0-dev
    stage-packages:
      - libc6
